spring:
  datasource:
    url: ENC(jVmJwJpId/wCyK8TrdHfbkWWnfZuL743Q1yn3yU/biIdB+ixvvizz+29jTkNlGuXx9hxYoJKZTRwofe8zEeXxTviLDo7O9a+ycEur14mNowf24MXgF+VjeFZZKptpUMR)
    username: root
    password: ENC(6VZm7XOLLBv2ImqSYHS2iz+HRC4GDMmI)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true     # Hibernate? ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true  # ???? SQL? ?? ?? ??
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8? Hibernate ?? ??


  datasource.hikari:
    maximum-pool-size: 10       # ?? ??? ? ??
    minimum-idle: 2       # ?? ?? ??? ?
    idle-timeout: 30000       # ?? ???? ?? ?? ?? (???)
    pool-name: HikariCP       # ??? ? ??
    max-lifetime: 600000       # ???? ?? ?? (???)
    connection-timeout: 30000      # ???? ?? ?? ?? ?? ?? (???)

