spring:
  datasource:
    url: ENC(css/Qv1AFynp6ZHKwhIVbzt/uaJQFGdrZlG1rwQPJRJMJLi9hx5dNBqkDP8Gezl5UC0DGyKpZ0e/dsrvSmwSBvkwXM9bLifCyWd7H6DZL2Dl0Xk9M9AXvFJ1tF3o1bQj)
    username: root
    password: ENC(6VZm7XOLLBv2ImqSYHS2iz+HRC4GDMmI)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true     # Hibernate? ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true  # ???? SQL? ?? ?? ??
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8? Hibernate ?? ??


  datasource.hikari:
    maximum-pool-size: 10       # ?? ??? ? ??
    minimum-idle: 2       # ?? ?? ??? ?
    idle-timeout: 30000       # ?? ???? ?? ?? ?? (???)
    pool-name: HikariCP       # ??? ? ??
    max-lifetime: 600000       # ???? ?? ?? (???)
    connection-timeout: 30000      # ???? ?? ?? ?? ?? ?? (???)

